name: CI

on:
    pull_request: ~
    push:
        branches:
            - '*'
        tags:
            - '*'
    schedule:
        - cron: 0 13 * * MON

jobs:
    cs:
        name: Coding Style
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2

            - name: Checkout
              uses: actions/checkout@v2

            - name: Install ecs
              run: cd tools/ecs && composer install --no-interaction --no-suggest
                
            - name: Run the CS fixer
              run: composer cs-fixer

    tests:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        strategy:
            fail-fast: false
            matrix:
                php: [8.1, 8.2]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Checkout
              uses: actions/checkout@v2

            - name: Install phpunit
              run: cd tools/phpunit && composer install --no-interaction --no-suggest

            - name: Install the dependencies
              run: composer install --no-interaction --no-suggest

            - name: Run the unit tests
              run: composer unit-tests

    prefer-lowest-tests:
        name: PHP ${{ matrix.php }} --prefer-lowest
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        strategy:
            fail-fast: false
            matrix:
                php: [8.1, 8.2]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Checkout
              uses: actions/checkout@v2

            - name: Install phpunit
              run: cd tools/phpunit && composer install --no-interaction --no-suggest

            - name: Install the dependencies
              run: composer update --prefer-lowest --prefer-stable --no-interaction --no-suggest

            - name: Run the unit tests
              run: composer unit-tests
